{
 "title": "Tailnet Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Running Services",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "entrypoint_num_reverse_proxies", "legendFormat": "Reverse Proxies" },
    { "expr": "entrypoint_num_streams", "legendFormat": "Streams" },
    {
     "expr": "sum by (service) (count(service_health_status >= 8))",
     "legendFormat": "Unhealthy"
    },
    { "expr": "router_http_req_total", "legendFormat": "Requests Processed" }
   ]
  },
  {
   "title": "Network",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_network_receive_bytes_total",
     "legendFormat": "Received"
    },
    {
     "expr": "process_network_transmit_bytes_total",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "go_memstats_sys_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "2xx-3xx Requests Processed",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(service) (router_http_req_ok_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4xx Requests Processed",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 4, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(service) (router_http_req_4xx_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx Requests Processed",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 4, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(service) (router_http_req_5xx_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Time Elapsed 95th Percentile",
   "type": "stat",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "quantile by(service) (0.95, router_http_req_elapsed_ms)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Visitors' Requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by(visitor) (router_http_req_ok_count))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Health",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "sum by(service) (label_replace(service_health_status, \"service\", \"$2\", \"service\", \"(.+)/(.+)\"))",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}